# 站点基础信息
site_name: ChatDocs
site_url: https://veryshuai666.github.io/ChatDocs/
site_description: 开发文档
site_author: misery

# 主题配置
theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - code.highlight
  palette:
    - scheme: default
      primary: blue

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify
  - codehilite:
      guess_lang: false
  - admonition


nav:
  - 🏠 首页: index.md
  - 📋 接口文档:
      - 接口文档: 接口文档/接口文档.md
  - 🔐 认证授权:
      - RefreshToken 模式规划: Refresh token模式/基于jwt -cpp 实现 Refresh token模式.md
      - RefreshToken 代码实现: Refresh token模式/Refresh token模式的实现.md
  - 🌐 WebSocket通信:
      - 连接断连与回收机制 规划: Websocket连接管理/Websocket 连接过期和回收机制.md
      - 连接断连与回收机制 实现: Websocket连接管理/Websocket连接过期机制实现.md
  - 📨 消息处理系统:
      - 转发分类与投递策略: 消息处理/消息转发分类和投递策略.md